Repository joh-ann/rancid-tomatillos, pull requests merged in 2023-10, with the labels that each got.

#15 Feat/wireframe
  src/components/AllMovies/AllMovies.css
  src/components/AllMovies/AllMovies.js
  src/components/App/App.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/Card/Card.test.js
  src/components/Cards/Cards.js
  src/components/Cards/Cards.test.js
  src/components/Footer/Footer.js
  src/components/Header/Header.js
  src/index.js
  src/movieData.js
Labels: Iteration 1

#16 Focus Movie Functionality in console log
  src/components/AllMovies/AllMovies.js
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/FocusMovie/FocusMovie.js
Labels: Iteration 2

#17 Render single movie
  src/components/FocusMovie/FocusMovie.js
Labels: Iteration 2

#18 Add styling for AllMovies
  src/components/AllMovies/AllMovies.css
  src/components/AllMovies/AllMovies.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/Card/Card.css
  src/components/Card/Card.js
Labels: enhancement, Iteration 2

#19 Feat/styling
  src/components/AllMovies/AllMovies.css
  src/components/App/App.css
  src/components/Card/Card.css
  src/components/Card/Card.js
Labels: enhancement, Iteration 2

#20 Add styling to header
  src/components/Header/Header.css
  src/components/Header/Header.js
Labels: enhancement

#21 Add styling to footer. Needs a bit morework
  src/components/App/App.css
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
Labels: enhancement

#22 Feat/modal
  package-lock.json
  package.json
  src/components/AllMovies/AllMovies.css
  src/components/App/App.css
  src/components/App/App.js
  src/components/FocusMovie/FocusMovie.css
  src/components/FocusMovie/FocusMovie.js
Labels: enhancement, Iteration 2

#23 Feat/fetch data
  src/components/App/App.css
  src/components/App/App.js
  src/components/FocusMovie/FocusMovie.js
Labels: enhancement, Iteration 3

#24 Continue styling the footer components
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
Labels: enhancement, Iteration 3

#25 Continue styling the header component
  src/components/Header/Header.css
  src/components/Header/Header.js
Labels: enhancement, Iteration 3

#26 Add movie trailer
  src/components/App/App.css
  src/components/App/App.js
  src/components/FocusMovie/FocusMovie.css
  src/components/FocusMovie/FocusMovie.js
Labels: enhancement, Iteration 3

#29 Feat/typechecking
  package-lock.json
  package.json
  src/components/AllMovies/AllMovies.js
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/FocusMovie/FocusMovie.js
Labels: enhancement, Iteration 3

#30 Change paragraph styles on the footer
  src/components/App/App.css
  src/components/Footer/Footer.css
Labels: enhancement

#31 Feat/modal
  src/components/App/App.css
  src/components/Card/Card.css
  src/components/FocusMovie/FocusMovie.css
  src/components/FocusMovie/FocusMovie.js
Labels: enhancement, Iteration 3

#33 Modal/Header/Footer styling
  public/index.html
  src/components/App/App.css
  src/components/Card/Card.css
  src/components/FocusMovie/FocusMovie.css
  src/components/FocusMovie/FocusMovie.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/Header.css
  src/components/Header/Header.js
Labels: enhancement, Iteration 3

#34 Add our first cypress tests to home page
  cypress.config.js
  cypress/e2e/about.cy.js
  cypress/e2e/home.cy.js
  cypress/e2e/search.cy.js
  cypress/fixtures/example.json
  cypress/fixtures/moviedata.json
  cypress/fixtures/singlemovie.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: Cypress Testing

#35 Add routing to render home page
  package-lock.json
  package.json
  src/components/About/About.css
  src/components/About/About.js
  src/components/App/App.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/index.js
Labels: Iteration 4

#48 Started adding content and styles to about page
  src/components/About/About.css
  src/components/About/About.js
  src/components/FocusMovie/FocusMovie.js
  src/data/dee_johann.png
  src/data/hochworter_ann.jpg
  src/data/images.js
Labels: Iteration 4

#49 Feat/search
  src/components/App/App.js
  src/components/Header/Header.js
  src/components/Search/Search.css
  src/components/Search/Search.js
  src/components/Search/Search.test.js
Labels: Choose Your Own Adventure

#56 Feat/styling
  cypress/downloads/downloads.html
  package-lock.json
  package.json
  public/favicon.ico
  src/components/About/About.css
  src/components/About/About.js
  src/components/AllMovies/AllMovies.test.js
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/Card/Card.test.js
  src/components/FocusMovie/FocusMovie.js
  src/components/FocusMovie/FocusMovie.test.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Footer/Footer.test.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Header/Header.test.js
  src/components/Logo/Logo.css
  src/components/Logo/Logo.js
  src/components/Logo/Logo.test.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
  src/components/Navbar/Navbar.test.js
  src/components/ReactBuilt/ReactBuilt.css
  src/components/ReactBuilt/ReactBuilt.js
  src/components/Search/Search.css
  src/components/Search/Search.js
  src/components/Search/Search.test.js
  src/data/images.js
  src/images/dee_johann.png
  src/images/github.png
  src/images/hochworter_ann.jpg
  src/images/linkedin.png
  src/images/logo512.png
  src/images/tomatillo.png
Labels: enhancement, Iteration 4

#57 Expand PropTypes to include shaped and arrayOf
  src/components/AllMovies/AllMovies.js
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/FocusMovie/FocusMovie.js
  src/components/Header/Header.js
Labels: enhancement, Iteration 3, Iteration 4

#58 Feat/styling
  src/components/About/About.css
  src/components/AllMovies/AllMovies.css
  src/components/Card/Card.css
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/Header.css
Labels: enhancement, Iteration 4

#59 Feat/typechecking
  cypress/e2e/about.cy.js
  cypress/e2e/home.cy.js
  cypress/e2e/search.cy.js
  src/components/FocusMovie/FocusMovie.js
  src/components/Header/Header.js
Labels: Iteration 4

#60 Add proptypes to search and header
  src/components/AllMovies/AllMovies.js
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/FocusMovie/FocusMovie.js
  src/components/Header/Header.js
  src/components/Search/Search.js
Labels: enhancement, Iteration 4

#61 Feat/fixes
  public/favicon.ico
  public/index.html
  src/components/About/About.css
  src/components/About/About.js
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/FocusMovie/FocusMovie.css
  src/components/FocusMovie/FocusMovie.js
  src/components/Footer/Footer.css
  src/components/Header/Header.css
  src/components/Search/Search.js
Labels: bug, Choose Your Own Adventure

#63 Add 404 and 500 error checks in cypress
  cypress/e2e/home.cy.js
  src/components/App/App.js
Labels: Iteration 4

#64 Refactor/api calls
  src/apiCalls.js
  src/components/App/App.js
Labels: Iteration 4

#65 Add alt tags to images
  src/components/Card/Card.js
  src/components/FocusMovie/FocusMovie.js
  src/components/Footer/Footer.js
  src/components/Header/Header.js
  src/components/ReactBuilt/ReactBuilt.js
Labels: Iteration 4

#66 Feat/styling
  src/apiCalls.js
  src/components/About/About.css
  src/components/App/App.css
  src/components/App/App.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/FocusMovie/FocusMovie.css
  src/components/FocusMovie/FocusMovie.js
  src/components/Search/Search.css
  src/components/Search/Search.js
Labels: enhancement

#67 Feat/styling
  src/components/FocusMovie/FocusMovie.js
Labels: enhancement
